<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cho php_antsomi-slidedown-cancel-button</name>
   <tag></tag>
   <elementGuidId>49cc0d4e-e94c-47d5-a2d9-141bcbd01ec2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#antsomi-slidedown-cancel-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='antsomi-slidedown-cancel-button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Bỏ qua&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>50cbc4c6-e973-40fe-9c86-56e689676224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right secondary slidedown-button</value>
      <webElementGuid>a777665b-376b-4d19-b91e-0cc874d0cdb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antsomi-slidedown-cancel-button</value>
      <webElementGuid>4e732f69-bf67-4b95-b3c0-9d52dc5cf17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bỏ qua</value>
      <webElementGuid>4fd2c449-c7e8-4635-8d47-75cbdd5f7dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antsomi-slidedown-cancel-button&quot;)</value>
      <webElementGuid>0903d8d6-526c-4e8d-b42f-091aad1295c8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='antsomi-slidedown-cancel-button']</value>
      <webElementGuid>805a5217-9853-428e-b90d-505b71355529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button[2]</value>
      <webElementGuid>c690dd31-d6e6-45ec-9c39-74af38d3a9f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cho phép'])[1]/following::button[1]</value>
      <webElementGuid>6d15c219-97c4-4ad4-ad5f-85e6fb739c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhận thông báo mới nhất về các chương trình khuyến mãi tại Aristino!'])[1]/following::button[2]</value>
      <webElementGuid>d75bf4bc-ddae-4a64-a38e-02092e499c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Văn bản gốc'])[1]/preceding::button[1]</value>
      <webElementGuid>9c98790a-819e-4fd6-b5d8-fccf2740d63b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá bản dịch này'])[1]/preceding::button[1]</value>
      <webElementGuid>e3ac91f8-31fa-415b-95ca-15843609654b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bỏ qua']/parent::*</value>
      <webElementGuid>f70bf177-3571-4cb5-ab43-522e4a64f2ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/div/div[2]/button[2]</value>
      <webElementGuid>cff3593c-8907-4295-b069-99db81c22057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'antsomi-slidedown-cancel-button' and (text() = 'Bỏ qua' or . = 'Bỏ qua')]</value>
      <webElementGuid>d87b72c1-339e-4bc1-886d-40297f5ae76e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
