<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_numProdyuct</name>
   <tag></tag>
   <elementGuidId>5ebe01c2-02cf-4775-b6d9-a13904d37d90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#updates_1162156798</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='updates_1162156798']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#updates_1162156798</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>91d15fa1-361c-4499-a9f9-fd0f3ce091b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-vid</name>
      <type>Main</type>
      <value>1162156798</value>
      <webElementGuid>35fc47b5-4734-48a7-952e-428b7d298316</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-quantity</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>6e924dfa-520f-4160-b516-faf52dd3f72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-product</name>
      <type>Main</type>
      <value>1071550842</value>
      <webElementGuid>eabad86e-c205-4895-a6cb-816c2fab2658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>304c4a4b-17b9-493b-a9b7-f18d008d338f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3ea0bd1c-110a-4382-94e7-90dd2267c6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>updates[]</value>
      <webElementGuid>9b7c9789-2cba-41c6-a194-f20fe360d29a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>4af7dc66-bb2e-47d1-b630-3ba4f1c3dca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>updates_1162156798</value>
      <webElementGuid>eb895601-29e2-416b-b56a-db6f392e7559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-price</name>
      <type>Main</type>
      <value>224400000</value>
      <webElementGuid>23a8613e-7d85-4a1b-bbfe-3ed407cb476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>cf47c5a5-5171-4601-9046-864e46925d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc line-item-qty item-quantity-mini</value>
      <webElementGuid>4740258a-4d94-4bae-9199-68f2faed1d68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;updates_1162156798&quot;)</value>
      <webElementGuid>fa997a02-afa5-4c88-b658-ae31cf69bc17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='updates_1162156798']</value>
      <webElementGuid>44787bb7-7217-4fb8-8683-711ae54d5a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart']/div/div[2]/div/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>708252fd-725a-4801-a4e2-29066ce531ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/input</value>
      <webElementGuid>1581d6e6-bf46-4f0b-a52b-27a9f3c1c002</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'updates[]' and @id = 'updates_1162156798']</value>
      <webElementGuid>4fe8f66f-347b-4453-b4f3-34c24bce8166</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
