<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>seizeM</name>
   <tag></tag>
   <elementGuidId>806bc46b-489a-464c-9137-16ca9190fe00</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;option_2_1162156798&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='option_2_1162156798']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>select[name=&quot;option_2_1162156798&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3261c453-d66e-4757-ae77-1e390aba8343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>option_2_1162156798</value>
      <webElementGuid>3efb960b-94a2-4a7f-8bae-6dfa11da1716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prd</name>
      <type>Main</type>
      <value>1071550842</value>
      <webElementGuid>6a2fcc22-d440-47a9-9323-70eadd4e716f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-line</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>36d38ad6-cf42-4a05-9ddb-888e3b28a751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SMLXLXXL</value>
      <webElementGuid>bcb929d8-24e6-425a-80b7-1c4ed295ef7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart&quot;)/div[@class=&quot;sidebar-nav&quot;]/div[@class=&quot;sidebar-body&quot;]/div[@class=&quot;list-minicart ajaxMinicart&quot;]/div[@class=&quot;cart-group single&quot;]/div[@class=&quot;item line-item&quot;]/div[@class=&quot;right&quot;]/div[@class=&quot;item-meta&quot;]/div[@class=&quot;list-variant&quot;]/div[@class=&quot;variant-option&quot;]/select[1]</value>
      <webElementGuid>1da64f49-13c0-43fa-88cd-fdc571b93f06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='option_2_1162156798']</value>
      <webElementGuid>bf31a0f6-12c3-442f-8e1d-4cb1247d6358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart']/div/div[2]/div/div/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>b408503c-6c95-440b-b6d3-031e1cc054f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Áo Khoác 2 lớp Nam Nâu Aristino Regular Fit AJK606EDP01'])[4]/following::select[2]</value>
      <webElementGuid>93541a86-80ab-473d-980c-b233ed5861f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aristino'])[14]/following::select[2]</value>
      <webElementGuid>69fa6569-6fb1-49ef-9957-921c9bf77714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền hàng'])[1]/preceding::select[1]</value>
      <webElementGuid>d0776a2d-a43c-48a0-8dea-d3450da50f2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Phí vận chuyển'])[1]/preceding::select[1]</value>
      <webElementGuid>20e9d4c7-8c81-4320-93d6-2324f25beede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>50d0456f-8f85-428e-b4e6-8c9b784fbf8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'option_2_1162156798' and (text() = 'SMLXLXXL' or . = 'SMLXLXXL')]</value>
      <webElementGuid>f0060472-1697-4d33-a373-57764aff3a69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
