<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ONLINE</name>
   <tag></tag>
   <elementGuidId>264a71bd-0372-44d8-9428-390f87efeb3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='answer-id-cyaeroslrm']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#answer-id-cyaeroslrm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;ONLINE&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9f48b37-fef3-41ab-9db7-cd68b28d9056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>42e3e3ef-79bc-43b6-842f-4773728efb72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>answer-id-cyaeroslrm</value>
      <webElementGuid>831bacb8-e03e-4c7b-ad88-9253926fc4f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer4</value>
      <webElementGuid>d33df57e-b4f6-4c5a-8d7e-67d38305fde0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>ONLINE</value>
      <webElementGuid>c418f638-cd7a-44cc-bd0d-272205f8084f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;answer-id-cyaeroslrm&quot;)</value>
      <webElementGuid>ee8cca7f-9b2b-4880-94d2-63fcd1b71aa3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='answer-id-cyaeroslrm']</value>
      <webElementGuid>97855fa1-4441-40b3-a174-19f8f0c587c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/input</value>
      <webElementGuid>db18319b-023e-48eb-9ee0-29957d7e3f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'answer-id-cyaeroslrm' and @name = 'answer4']</value>
      <webElementGuid>e0801598-040f-47cf-a0c4-0f996950ac77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
