<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SHOWROOM</name>
   <tag></tag>
   <elementGuidId>16d5ff39-d0f6-4fa6-8978-2ceeed4ba689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#answer-id-anfszufnke</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='answer-id-anfszufnke']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;SHOWROOM&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2a08b0a-7091-41bd-92e5-bbfd36779d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>640ea0e0-45e8-433e-bea7-6a19c36ee766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>answer-id-anfszufnke</value>
      <webElementGuid>c5c7e67d-15ea-4b05-9daf-dc969660a10c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>answer4</value>
      <webElementGuid>3d7c3bfa-99cb-48cb-aaca-c2cd34827126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>SHOWROOM</value>
      <webElementGuid>34c550f7-770f-45cc-911c-870314e36ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;answer-id-anfszufnke&quot;)</value>
      <webElementGuid>af5fbfea-87c2-4704-81f2-5b3f535b0903</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='answer-id-anfszufnke']</value>
      <webElementGuid>513cd824-2cd4-4701-b789-c8e9b7a01888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[3]/input</value>
      <webElementGuid>ce6f39ae-bb77-45be-9737-24532afdbd3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'answer-id-anfszufnke' and @name = 'answer4']</value>
      <webElementGuid>380d45d2-7d0f-43b9-a5d2-e5f93b245ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
