<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__share_review_product</name>
   <tag></tag>
   <elementGuidId>753a1dcf-e08d-4a46-a8ae-a78ef5941a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='crv-hrvmodal--content-rating']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#crv-hrvmodal--content-rating</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Hãy chia sẻ đánh giá của bạn về sản phẩm&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b63c14b9-9e69-4b19-99dc-e235e165cb97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>crv-hrvmodal--content-rating</value>
      <webElementGuid>3e3a7673-ec68-49f7-ae8e-09436d226e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>crv-hrvmodal--content-rating</value>
      <webElementGuid>9d24005f-ce7e-47be-a736-cb1c7de457a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>crv-content-rating</value>
      <webElementGuid>ed211a05-ac58-4a3b-972e-39c80af83432</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Hãy chia sẻ đánh giá của bạn về sản phẩm</value>
      <webElementGuid>f7da557c-3589-491a-9b1a-133ef6841464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;crv-hrvmodal--content-rating&quot;)</value>
      <webElementGuid>9e3b6e36-622e-474e-a642-15dbe2e05727</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='crv-hrvmodal--content-rating']</value>
      <webElementGuid>c3abcb43-7606-42d5-a88f-55453fbc98f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/textarea</value>
      <webElementGuid>be35b50b-6344-4941-b808-fc46642641da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'crv-hrvmodal--content-rating' and @name = 'crv-content-rating' and @placeholder = 'Hãy chia sẻ đánh giá của bạn về sản phẩm']</value>
      <webElementGuid>04148fd4-dce5-4216-b520-dcd0323f171f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
