<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_login_fail</name>
   <tag></tag>
   <elementGuidId>8fd1fdf5-d9cc-4839-9358-24d426cd8279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.error-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customer_login']/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Thông tin đăng nhập không hợp lệ&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b9d8d56d-563b-4b7b-bcba-d8c80e6e395b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>error-status</value>
      <webElementGuid>65c225d3-de81-4492-9f99-ae3d0d96dfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Thông tin đăng nhập không hợp lệ</value>
      <webElementGuid>119c7347-a9e8-4df8-bcf5-04730403b0b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;error-status&quot;]</value>
      <webElementGuid>90fccef2-66ba-4b87-92eb-5cf56c8b03f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[4]</value>
      <webElementGuid>93a744f5-c258-4ad3-95cf-0dea6de617e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật Khẩu*'])[1]/following::div[1]</value>
      <webElementGuid>4372af77-53d5-4383-8224-ef1a71a04ef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email*'])[1]/following::div[2]</value>
      <webElementGuid>66a930ac-cd39-49b6-b748-77fa8cd8acdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/preceding::div[1]</value>
      <webElementGuid>fa26796b-8c7e-4dd4-91ea-8290d737dbdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quên mật khẩu'])[1]/preceding::div[1]</value>
      <webElementGuid>c414e556-0eb5-4885-9f08-1d62e52ae7cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Thông tin đăng nhập không hợp lệ']/parent::*</value>
      <webElementGuid>f544aa37-b837-44ce-bd77-2666f462b580</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[4]</value>
      <webElementGuid>ff6b703f-03ec-41ad-992f-702dc4de9e20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Thông tin đăng nhập không hợp lệ' or . = 'Thông tin đăng nhập không hợp lệ')]</value>
      <webElementGuid>12df6e67-b2a4-450a-9e1a-6a8787ae02b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
