<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>alert_nitification</name>
   <tag></tag>
   <elementGuidId>1b050983-3f89-476c-98c6-4756bfc835a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='antsomi-slidedown-dialog']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#antsomi-slidedown-dialog</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#antsomi-slidedown-dialog</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ebdb8254-71ef-4ebe-8694-59525ab39dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antsomi-slidedown-dialog</value>
      <webElementGuid>6bb37879-6586-44d5-a479-9c7399f47aa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>antsomi-slidedown-dialog</value>
      <webElementGuid>6be3a124-e76f-489b-a247-2fcbe36717f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nhận thông báo mới nhất về các chương trình khuyến mãi tại Aristino!Cho phépBỏ qua</value>
      <webElementGuid>34a44fed-b027-41f7-8cc4-04df25507074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antsomi-slidedown-dialog&quot;)</value>
      <webElementGuid>e3b7a275-784b-49e5-a779-7b4ca79025c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='antsomi-slidedown-dialog']</value>
      <webElementGuid>1cc46f88-f834-48e6-a6a2-4bdc5ca18bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='antsomi-slidedown-container']/div</value>
      <webElementGuid>9783130a-632b-4999-aee7-817f42f704f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[1]/following::div[26]</value>
      <webElementGuid>5784d9d4-385c-4197-a33f-96863abc93d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div</value>
      <webElementGuid>dfaca787-f534-486f-9569-1eca1aa43cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'antsomi-slidedown-dialog' and (text() = 'Nhận thông báo mới nhất về các chương trình khuyến mãi tại Aristino!Cho phépBỏ qua' or . = 'Nhận thông báo mới nhất về các chương trình khuyến mãi tại Aristino!Cho phépBỏ qua')]</value>
      <webElementGuid>2cc766b9-0900-4725-8151-41a714879035</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
