<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>product</name>
   <tag></tag>
   <elementGuidId>06ea653e-57a1-4491-a03e-03383221518a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pro-loop--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-page']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.pro-loop--link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a9a076e2-ca49-48b5-a52d-40d443f1493a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01</value>
      <webElementGuid>fe3f4c1d-d445-4d3d-923f-ce43a93de526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pro-loop--link</value>
      <webElementGuid>98e90600-bc62-4473-a25b-f49871123474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-page&quot;)/div[@class=&quot;collection-wrapper&quot;]/div[@class=&quot;collection-body&quot;]/div[@class=&quot;container-fluid p8&quot;]/div[@class=&quot;d-flex flex-wrap push-section&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;filter-wrapper--grid ajax-render&quot;]/div[@class=&quot;grid-products&quot;]/div[@class=&quot;pro-tile pro-loop pro-t1 1&quot;]/div[@class=&quot;pro-loop--wrap&quot;]/div[@class=&quot;pro-loop--head&quot;]/a[@class=&quot;pro-loop--link&quot;]</value>
      <webElementGuid>44bf00df-6b0f-4011-ac44-29127cb97805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-page']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>23109818-2ecb-46ef-bbc3-9d7ce314c1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01')]</value>
      <webElementGuid>08c0769b-a78d-42df-bdb9-8c848c40a649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>b01bd8f3-c9a4-4049-9026-e4c82c0727cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01']</value>
      <webElementGuid>c26e2be4-07db-4258-9cb5-69f0f30b4c95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
