<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ThemDiaChi</name>
   <tag></tag>
   <elementGuidId>ee248bd5-d512-446c-81e8-49cfba0cc220</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#js-btn-addnew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='js-btn-addnew']//span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Thêm địa chỉ&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>02f6da1e-cb55-41ed-9e48-ae48337bcdcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>606c7bd9-ee1d-447e-a5e8-5a86327fdc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-addnew</value>
      <webElementGuid>526701ac-ead7-46df-a3a0-84216e0eac1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>js-btn-addnew</value>
      <webElementGuid>87c9f2b9-97ff-40db-a898-d90f557fa1c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Thêm địa chỉ 
              </value>
      <webElementGuid>8beeb996-ef0c-4886-867b-90ffc4d9ec1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;js-btn-addnew&quot;)</value>
      <webElementGuid>6bba834d-0300-4848-aa8a-2065173a5b0d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='js-btn-addnew']//span</value>
      <webElementGuid>f9fae8d4-2d42-44bb-aee5-e755ef5d3db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mặc định'])[1]/following::a[1]</value>
      <webElementGuid>3b153516-1ba1-4bb5-8caa-26775ec0764d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Văn phòng'])[1]/following::a[1]</value>
      <webElementGuid>6890c0db-50a1-4ea2-a171-8cc54cf9a508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ĐỊA CHỈ MỚI'])[1]/preceding::a[1]</value>
      <webElementGuid>3a76f5de-a0be-4989-99e5-b9e7d69822fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>fde3e220-1997-466a-b2d0-59680ff80725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/a</value>
      <webElementGuid>341c818f-1310-476b-9067-295b36a6adb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'js-btn-addnew' and (text() = '
                Thêm địa chỉ 
              ' or . = '
                Thêm địa chỉ 
              ')]</value>
      <webElementGuid>51373b21-24fa-4700-a6bc-5d88878edfcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
