<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_birthday</name>
   <tag></tag>
   <elementGuidId>17add27d-ea49-4a72-8eed-cd51976c8d8f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ngày sinh (DD/MM/YYYY)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>03d3369b-fd29-4c80-ab87-0be47b481541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d67b0b87-a29e-4412-a223-128649da0f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập ngày tháng năm</value>
      <webElementGuid>f363655a-041a-4ad2-aa23-9d8f68d6183d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>86c08d78-880e-429d-a45b-33a72f4c45b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>c3e7d933-dad9-4f61-b68e-e2fd086bf305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>f1d6b2d1-c287-45b7-a707-8100aa9f20f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_customer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-12&quot;]/div[@class=&quot;item-input-form&quot;]/input[@id=&quot;birthday&quot;]</value>
      <webElementGuid>5339173f-89c3-4e2c-b18c-9e38c29ac0fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday']</value>
      <webElementGuid>95d42bea-26cd-4ff4-b760-d4ff2338398e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='update_customer']/div/div[4]/div/input</value>
      <webElementGuid>4cd0320b-a3ba-4798-966e-f738574474f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>b2ddf6df-26f7-48be-9102-c1595ca40bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập ngày tháng năm' and @name = 'birthday' and @id = 'birthday']</value>
      <webElementGuid>85dd6972-8bfe-420e-a13d-7bffa8f903aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
