<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Nhn thng bo mi nht v cc chng trnh kh_31a3bc</name>
   <tag></tag>
   <elementGuidId>87aa80f1-2dd1-4d7e-831b-0d3eea7835a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'antsomi-slidedown-allow-button' and (text() = 'Cho phép' or . = 'Cho phép')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='antsomi-slidedown-allow-button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#antsomi-slidedown-allow-button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Cho phép&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ad3d3edd-bcdd-46ef-86dc-027510257d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>align-right primary slidedown-button</value>
      <webElementGuid>d3105353-8fb3-44a8-b66b-3143b09d8beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>antsomi-slidedown-allow-button</value>
      <webElementGuid>ebc5f0b8-dfa0-4db6-adc0-4c1f46e5918e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cho phép</value>
      <webElementGuid>eeae1cc0-f9ec-451d-984f-c0981f1cedf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;antsomi-slidedown-allow-button&quot;)</value>
      <webElementGuid>07650cc0-7818-4d6f-b073-5071b87fd544</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='antsomi-slidedown-allow-button']</value>
      <webElementGuid>516b60a0-133d-4b6e-ae3d-b275de756189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='slidedown-footer']/button</value>
      <webElementGuid>99715dd9-3a54-47ce-a92e-07c851e6951f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nhận thông báo mới nhất về các chương trình khuyến mãi tại Aristino!'])[1]/following::button[1]</value>
      <webElementGuid>77e4ba06-eb3e-4aae-9c32-122fd6ffa544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ý kiến phản hồi của bạn sẽ được dùng để góp phần cải thiện Google Dịch'])[1]/following::button[3]</value>
      <webElementGuid>60afaad8-eb75-4750-bc54-bff4eb503558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ qua'])[1]/preceding::button[1]</value>
      <webElementGuid>d5d392b0-309c-4cdd-a451-f3d39f8c565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cho phép']/parent::*</value>
      <webElementGuid>66a4bc42-c680-4528-acab-d0154e90de6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/div/div[2]/button</value>
      <webElementGuid>037499da-1772-42bb-beca-29c7b78ed3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'antsomi-slidedown-allow-button' and (text() = 'Cho phép' or . = 'Cho phép')]</value>
      <webElementGuid>a091ef5d-9419-44e0-8a36-9a13b802f3c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
