<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_kin phn hi ca bn s c dng  gp phn ci thi_c5157c</name>
   <tag></tag>
   <elementGuidId>3384f088-6ecc-4f94-a7f6-1db5f42765a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;mt-83266-ex8qfubn76-ybmildkcea-campaign&quot;)/div[@class=&quot;styled__CloseButtonWrapper-sc-m09mre-0 boWLNi template-close&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mt-83266-ex8qfubn76-ybmildkcea-campaign']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.styled__CloseButtonWrapper-sc-m09mre-0.boWLNi.template-close</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.styled__CloseButtonWrapper-sc-m09mre-0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8a5d3c87-fadf-4cc4-97af-adc14506c0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>styled__CloseButtonWrapper-sc-m09mre-0 boWLNi template-close</value>
      <webElementGuid>995fb33a-a8f8-4b9e-98dd-ad7bd6f88fea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mt-83266-ex8qfubn76-ybmildkcea-campaign&quot;)/div[@class=&quot;styled__CloseButtonWrapper-sc-m09mre-0 boWLNi template-close&quot;]</value>
      <webElementGuid>e2ddef2c-f464-470b-a9d5-9bb43ba447e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mt-83266-ex8qfubn76-ybmildkcea-campaign']/div</value>
      <webElementGuid>c7026a49-f282-485e-b638-00c387d201a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ý kiến phản hồi của bạn sẽ được dùng để góp phần cải thiện Google Dịch'])[1]/following::div[12]</value>
      <webElementGuid>90d9d2b2-a812-40d9-8ee5-7f76c89a8dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá bản dịch này'])[1]/following::div[13]</value>
      <webElementGuid>4c28456f-d3f5-4b3b-a5bf-1285ac9e9cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div/div/div/div/div/div</value>
      <webElementGuid>b82db929-92d8-471f-a94f-70c2832bab52</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
