<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_phone</name>
   <tag></tag>
   <elementGuidId>87d0a196-5c6c-4264-99fb-75d981af96d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hrv-crv-customer__phone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hrv-crv-customer__phone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Số điện thoại (không hiển thị trên website)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>910fda38-92be-45c6-b5f5-4812428d47c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrv-crv-customer__phone</value>
      <webElementGuid>dcbcbf4a-9ad4-44c5-96dc-ad2a6dd091b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tại đây</value>
      <webElementGuid>0b4319db-6138-4a6f-b172-9221cf592ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25f4f31b-6045-4a7b-ab0b-b07edf31fed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>phone</value>
      <webElementGuid>3cd0404b-e6fb-46a4-9378-e37376363426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>^(0|[1-9][0-9]*)</value>
      <webElementGuid>8618dfaf-ab82-4f10-ba8c-c45d1796dd74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrv-crv-customer__phone&quot;)</value>
      <webElementGuid>0caf222d-dda1-4168-a31f-18d2c6c542ab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hrv-crv-customer__phone']</value>
      <webElementGuid>f0b3a06d-0461-4ada-a523-99de96710cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/div[2]/input</value>
      <webElementGuid>ef90d6ff-fc6e-4ab1-a7d5-0ea76a1a6136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hrv-crv-customer__phone' and @placeholder = 'Nhập tại đây' and @type = 'text' and @name = 'phone']</value>
      <webElementGuid>217744dd-0934-4725-8a0c-62d93129093a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
