<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ten_hien_thi</name>
   <tag></tag>
   <elementGuidId>8d5845ef-e2e3-4f17-9ee3-a21db451e296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='hrv-crv-customer__name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hrv-crv-customer__name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Tên hiển thị*&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>82617f8f-b19d-443b-8967-bc62fad1e5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrv-crv-customer__name</value>
      <webElementGuid>1d24fae1-c0c0-4009-9018-8a5fb4ed942a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập tại đây</value>
      <webElementGuid>d1a01e86-8423-4dda-a7bb-a2d6b7fc6517</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9c2cd7b-060f-4de5-a4a9-a3306c853e1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>name</value>
      <webElementGuid>ca161e40-df3c-4e6d-a91a-300b82c17294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrv-crv-customer__name&quot;)</value>
      <webElementGuid>268cac7f-6104-4e45-beb0-d4989b1fb5d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='hrv-crv-customer__name']</value>
      <webElementGuid>4bf51a69-0092-4cd5-8b90-7b3fa1f0bebf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/input</value>
      <webElementGuid>33683f70-d8e9-438d-b4b4-78bda6666b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'hrv-crv-customer__name' and @placeholder = 'Nhập tại đây' and @type = 'text' and @name = 'name']</value>
      <webElementGuid>ea9273fe-0efd-4a1d-b761-0b5cf7f20417</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
