<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>saddtocart</name>
   <tag></tag>
   <elementGuidId>2a938ba9-9b4b-423a-b8ce-6399df341718</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-addtocart > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-addtocart']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt hàng trước&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>67463998-0471-4eae-b46f-6ee0c9897226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt hàng trước</value>
      <webElementGuid>8f51aa5c-839b-4c1c-977c-8c838e5e9e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-addtocart&quot;)/span[1]</value>
      <webElementGuid>92da2bc0-1ca7-48fd-998c-8facb1541d7c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn-addtocart']/span</value>
      <webElementGuid>68fbd240-981f-48fa-a0e3-e0db7d38cc04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXL'])[1]/following::span[1]</value>
      <webElementGuid>3ae02334-fe41-4ccb-9f5c-fc3c776ae0a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/following::span[1]</value>
      <webElementGuid>85978b1a-137d-43fb-971c-76740cbb14cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian giao hàng dự kiến'])[1]/preceding::span[1]</value>
      <webElementGuid>ac026978-3d43-4e8f-abed-c4022268e29d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Từ ngày 05.05.2025'])[1]/preceding::span[1]</value>
      <webElementGuid>c3d7e9ac-8608-4a3d-8e81-749c77c691d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đặt hàng trước']/parent::*</value>
      <webElementGuid>e8374292-d444-4cb4-801d-d1d2674b88c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>7849960f-87a8-4636-9605-5e22f8ea36c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Đặt hàng trước' or . = 'Đặt hàng trước')]</value>
      <webElementGuid>69de2e5f-e0dd-4eef-98d9-5aa885a93056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
