<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rating_5</name>
   <tag></tag>
   <elementGuidId>babd88a3-cf3c-49b6-8cab-1a4cbf92327e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.crv-hrvmodal--header__star > .hrv-crv-rating__groups > div:nth-child(5) > svg</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>a7caa8e5-e490-4562-ae33-9f5eb7905f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e8cc9786-0466-4a66-a3e7-503ca777b5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>659b7ffc-8746-489b-bea8-c1f027a84506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>60d1d3ce-d354-4248-a542-e2b7f850e075</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>bd0c74fb-e031-4131-9598-199db43ccca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 34 34</value>
      <webElementGuid>d43879e8-9b2e-43b8-81d8-275b2cd229fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>59ee47b9-5b85-4226-af58-e35ef6945e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>39cc950e-143b-4b16-a442-e954179949b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mainBody-theme temp-product&quot;]/div[@class=&quot;crv-hrvmodal crv-hrvmodal--dialog crv-hrvmodal__rating open&quot;]/div[@class=&quot;crv-hrvmodal--content&quot;]/div[@class=&quot;crv-hrvmodal--body&quot;]/div[@class=&quot;crv-hrvmodal--body-header&quot;]/div[@class=&quot;crv-hrvmodal--header__star&quot;]/div[@class=&quot;hrv-crv-rating__groups hrv-crv-modal&quot;]/div[@class=&quot;hrv-crv-rating__box active&quot;]/svg[1]</value>
      <webElementGuid>8c365056-160b-4339-aa41-924c19215fbd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][5]</value>
      <webElementGuid>2441043e-dff6-4956-92e3-f14db9d88b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá sản phẩm'])[2]/following::*[name()='svg'][6]</value>
      <webElementGuid>48dd6bf7-dc1f-4b9f-9d1d-a533dd71c27e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn mua hàng qua kênh nào'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>07c32458-a966-4e75-b19f-d59efb4f858e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>b89bf3b2-894b-4b33-b8d9-2b7c47b82daf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
