<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rating_4</name>
   <tag></tag>
   <elementGuidId>493683ad-14c9-4a3a-8536-2918449c6bd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.crv-hrvmodal--header__star > .hrv-crv-rating__groups > div:nth-child(4) > svg</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>238a34b1-0566-423b-a71c-5eb13a42b9c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7369c0d7-dbbc-4a43-97a2-edf60b04f967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>c634f120-20f7-450d-8cb1-4ab51cc8bbdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>e177e2fd-928f-4362-9f94-f42603584d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>ddfe4d3a-4799-49cc-b56c-112a2c761857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 34 34</value>
      <webElementGuid>d9e74aa9-4c70-4c42-8206-334c350f59b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>391d7b95-6039-4eb3-be04-8c9368f7e650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>fd42b20b-0aa6-41bc-ad8a-acea55f0b4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mainBody-theme temp-product&quot;]/div[@class=&quot;crv-hrvmodal crv-hrvmodal--dialog crv-hrvmodal__rating open&quot;]/div[@class=&quot;crv-hrvmodal--content&quot;]/div[@class=&quot;crv-hrvmodal--body&quot;]/div[@class=&quot;crv-hrvmodal--body-header&quot;]/div[@class=&quot;crv-hrvmodal--header__star&quot;]/div[@class=&quot;hrv-crv-rating__groups hrv-crv-modal&quot;]/div[@class=&quot;hrv-crv-rating__box active&quot;]/svg[1]</value>
      <webElementGuid>32605b3c-17eb-470d-ad01-f40202c631dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][4]</value>
      <webElementGuid>afbb6e26-d1ff-4984-b877-f440e91d0da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá sản phẩm'])[2]/following::*[name()='svg'][5]</value>
      <webElementGuid>b06283b7-8827-48ae-9072-d589bc7d7821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn mua hàng qua kênh nào'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>d74ba065-0762-42cd-9da6-b65557c68764</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>9acd30de-1b82-43bf-be21-54c43c507a3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
