<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rating_3</name>
   <tag></tag>
   <elementGuidId>6980d9a5-e977-4353-bc4a-155360c1bca2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.crv-hrvmodal--header__star > .hrv-crv-rating__groups > div:nth-child(3) > svg</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>fbe093ba-0cae-4cac-9075-564aac46f250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d99087ab-4f38-47e9-95b1-12a1f42081b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>abf3ed74-af33-48fc-a3cc-e36c7e911801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>22px</value>
      <webElementGuid>656064b7-6427-4d0d-861d-274fb88b69c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>2f3cd7c6-260e-41f2-8334-4cd200772074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 34 34</value>
      <webElementGuid>3f5a6cd9-9f02-4062-8293-e13187a62230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>50e6bdd4-4e25-4569-aad8-9a745a44698c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>508769c2-6c53-4c59-8b4c-37382fdd486e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mainBody-theme temp-product&quot;]/div[@class=&quot;crv-hrvmodal crv-hrvmodal--dialog crv-hrvmodal__rating open&quot;]/div[@class=&quot;crv-hrvmodal--content&quot;]/div[@class=&quot;crv-hrvmodal--body&quot;]/div[@class=&quot;crv-hrvmodal--body-header&quot;]/div[@class=&quot;crv-hrvmodal--header__star&quot;]/div[@class=&quot;hrv-crv-rating__groups hrv-crv-modal&quot;]/div[@class=&quot;hrv-crv-rating__box active&quot;]/svg[1]</value>
      <webElementGuid>342c27a3-dd7b-4d0b-ba56-dbdb361a513c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quần Jeans Nam Hiệu Ứng Giặt Mài Aristino Business Regular 1JN0010S0'])[4]/following::*[name()='svg'][3]</value>
      <webElementGuid>4d01a75c-d8fb-4224-b728-a1d7da8387d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá sản phẩm'])[2]/following::*[name()='svg'][4]</value>
      <webElementGuid>8a09fb27-868c-44c7-890a-94d603fdd8af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bạn mua hàng qua kênh nào'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>979ba2ac-b912-404a-b4bd-f3f843795206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ONLINE'])[1]/preceding::*[name()='svg'][3]</value>
      <webElementGuid>4b9076a9-ac88-4eb1-aeff-ba39de1d0554</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
