<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>abtn_forgot-pasword</name>
   <tag></tag>
   <elementGuidId>417a7570-f96a-4a31-bc13-60f695e9f5ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.redirect-btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='customer_login']/div[5]/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Quên mật khẩu&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8d23425d-615a-47dc-8c03-918aba16a42a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>redirect-btn</value>
      <webElementGuid>c3f9a3c9-d7ee-4fe5-8884-d930ebb5f87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>.forgotten-password</value>
      <webElementGuid>eefcb301-7ba9-4c8e-a308-cde71330fa54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>ddc00aca-7bc0-4862-9668-10a522ddae66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quên mật khẩu</value>
      <webElementGuid>7d066c5c-7898-478a-ac01-6f6be8aa7274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_login&quot;)/div[@class=&quot;item-input-form&quot;]/div[@class=&quot;redirect-form&quot;]/a[@class=&quot;redirect-btn&quot;]</value>
      <webElementGuid>dde6a7e3-6db2-42ea-90e3-9fd1efe66e8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customer_login']/div[5]/div/a</value>
      <webElementGuid>1ff8afcc-5c8f-4551-8179-3721ce4ab46c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Quên mật khẩu')]</value>
      <webElementGuid>62268efb-16c1-4615-8520-a975128ce057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập'])[1]/following::a[1]</value>
      <webElementGuid>0509bf83-b9ac-47cf-929f-1ce9b34b2eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mật Khẩu*'])[1]/following::a[1]</value>
      <webElementGuid>9e7b68c6-14c3-41c6-ad16-9f8d34eec581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập bằng email'])[1]/preceding::a[1]</value>
      <webElementGuid>27967eeb-ef27-45c2-9acc-748cd33e0807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng nhập qua Số điện thoại'])[1]/preceding::a[1]</value>
      <webElementGuid>25584a58-4c99-4624-bd60-b5ea36eee7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quên mật khẩu']/parent::*</value>
      <webElementGuid>dcdc7f31-7fb3-43ff-94d7-5219fdc97182</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[2]</value>
      <webElementGuid>00a42e64-af8c-4351-a713-677e777342bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a</value>
      <webElementGuid>e7f2f0a3-fa8b-4295-a956-9ae4c21c523a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0);' and (text() = 'Quên mật khẩu' or . = 'Quên mật khẩu')]</value>
      <webElementGuid>dab9b262-56dc-4343-abdf-c60c07e7afeb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
