<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Vuilongnhapthongtin</name>
   <tag></tag>
   <elementGuidId>35b5a7d0-d532-4d12-80c9-354e9011da0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hrv-crv-customer-helper</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div >> internal:has-text=/^Viết đánh giá\*0/500 ký tựVui lòng nhập thông tin$/ >> div >> nth=3</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01931f73-0b67-40ff-a838-9689322c7d3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hrv-crv-customer-helper</value>
      <webElementGuid>2dfa65a2-19d0-43c2-bf93-627c4b078472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vui lòng nhập thông tin</value>
      <webElementGuid>c2dc96f0-801d-40eb-b9a7-8cf6b2472993</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;mainBody-theme temp-product&quot;]/div[@class=&quot;crv-hrvmodal crv-hrvmodal--dialog crv-hrvmodal__rating open&quot;]/div[@class=&quot;crv-hrvmodal--content&quot;]/div[@class=&quot;crv-hrvmodal--body&quot;]/div[@class=&quot;hrv-crv-customer-groups-content invalid&quot;]/div[@class=&quot;hrv-crv-customer-helper&quot;]</value>
      <webElementGuid>63c79b11-2116-488f-96ed-fbb25c29f1f7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[1]/following::div[2]</value>
      <webElementGuid>129d8b9f-775c-44df-86d0-3b7a1311c893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(định dạng .jpg, .jpeg, .png)'])[1]/preceding::div[2]</value>
      <webElementGuid>aba5fa08-e603-4582-80f0-63048b60d1db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div[2]/div[4]/div[2]</value>
      <webElementGuid>77607982-4d52-4a65-805e-3f76b87325df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Vui lòng nhập thông tin' or . = 'Vui lòng nhập thông tin')]</value>
      <webElementGuid>05e66858-43a2-4eaa-80b7-3736d2a104eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
