<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_product-relative</name>
   <tag></tag>
   <elementGuidId>de75f7d4-7212-45fc-afc1-59fef7c769b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pro-loop--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='swiper-wrapper-997744c1cec46158']/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;1 / 12&quot;s >> internal:role=link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4615b75-b005-4a21-a307-c9ae1236d526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01</value>
      <webElementGuid>c3d28f77-a104-43f7-90f3-0d955115b9ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pro-loop--link</value>
      <webElementGuid>15effa6c-1a00-45ab-9143-841e0eca976b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-997744c1cec46158&quot;)/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;pro-loop&quot;]/div[@class=&quot;pro-loop--wrap&quot;]/div[@class=&quot;pro-loop--head&quot;]/a[@class=&quot;pro-loop--link&quot;]</value>
      <webElementGuid>6e68bbb3-40a7-4ae0-b3c2-02021f32afcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='swiper-wrapper-997744c1cec46158']/div/div/div/div/a</value>
      <webElementGuid>91813349-4eaf-4de1-8328-10305fec953b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01')]</value>
      <webElementGuid>4da20bef-21ff-419f-8b21-140e47831496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/a</value>
      <webElementGuid>d9bee105-0fca-437a-a053-946502a425c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01']</value>
      <webElementGuid>eaf16068-669a-4029-92ac-4733812b170e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
