<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Sinhnhat_birthday</name>
   <tag></tag>
   <elementGuidId>24d79df3-ff23-4d90-8c13-9cd3f8aabcb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#birthday</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='birthday']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Ngày sinh (DD/MM/YYYY)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8f463c96-74ef-443a-bf42-827c22b9f936</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8134ce2b-4829-445e-8b5b-c2e3215aaaaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Nhập ngày tháng năm</value>
      <webElementGuid>8e4a398e-692a-41c8-94b5-91f5e4a46334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>16/02/2003</value>
      <webElementGuid>0291c6f2-cf47-401d-9772-76e3600a9bca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>c47936fb-01e8-4a69-abbc-20220dcbcfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0e002967-d594-4071-a4e4-ba39e558feab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>birthday</value>
      <webElementGuid>09e84a09-7039-4b97-bdf2-036535785768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;update_customer&quot;)/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 col-12&quot;]/div[@class=&quot;item-input-form&quot;]/input[@id=&quot;birthday&quot;]</value>
      <webElementGuid>35fcc6e6-4cdd-4a0b-bcba-297d0678ccfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='birthday']</value>
      <webElementGuid>e80b3719-4784-47d6-97c1-a39b27d5fa64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='update_customer']/div/div[4]/div/input</value>
      <webElementGuid>d87b9a38-3ac7-4b7f-82df-23f4a4faf4b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>76bd718e-67a0-447d-8efb-a9fb00e370eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Nhập ngày tháng năm' and @name = 'birthday' and @id = 'birthday']</value>
      <webElementGuid>8ade9207-ea14-482f-8077-cd24153fc173</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
