<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_NEW_pro-loop</name>
   <tag></tag>
   <elementGuidId>d98675c4-9d9b-4be2-9645-b13e679ee075</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pro-loop--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='collection-page']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.pro-loop--link >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9beff4eb-062e-45ea-a73a-376b514c87c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/quan-jeans-nam-hieu-ung-giat-mai-aristino-business-regular-1jn0010s0</value>
      <webElementGuid>d7554364-9003-417c-963b-78213feab58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pro-loop--link</value>
      <webElementGuid>5e391cd5-ad30-418d-afdd-d2a7ebb07472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;collection-page&quot;)/div[@class=&quot;collection-wrapper&quot;]/div[@class=&quot;collection-body&quot;]/div[@class=&quot;container-fluid p8&quot;]/div[@class=&quot;d-flex flex-wrap push-section&quot;]/div[@class=&quot;results-section&quot;]/div[@class=&quot;filter-wrapper--grid ajax-render&quot;]/div[@class=&quot;grid-products&quot;]/div[@class=&quot;pro-tile pro-loop pro-t1 1&quot;]/div[@class=&quot;pro-loop--wrap&quot;]/div[@class=&quot;pro-loop--head&quot;]/a[@class=&quot;pro-loop--link&quot;]</value>
      <webElementGuid>64c7506d-bedb-4ca9-8a35-f1abe8036199</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='collection-page']/div/div[2]/div/div/div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>438c7487-5e6a-4000-9c48-81824526aa08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/quan-jeans-nam-hieu-ung-giat-mai-aristino-business-regular-1jn0010s0')]</value>
      <webElementGuid>8b8269fb-7524-4a8d-aebe-5f628a733320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/a</value>
      <webElementGuid>1e8a0f23-0249-43bc-8335-9fe0e18ff067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/quan-jeans-nam-hieu-ung-giat-mai-aristino-business-regular-1jn0010s0']</value>
      <webElementGuid>b474dfb5-e6aa-49d6-a379-7ffd99a3c54c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
