<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_product-relative</name>
   <tag></tag>
   <elementGuidId>de75f7d4-7212-45fc-afc1-59fef7c769b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.pro-loop--link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@id, 'swiper-wrapper')]/div/div/div/div/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@href = '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>//div[@id='swiper-wrapper-997744c1cec46158']/div/div/div/div/a</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>360f0d48-f425-449c-96a4-f72d04898c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01</value>
      <webElementGuid>de3cebde-9977-48e5-8f48-a54311e9ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pro-loop--link</value>
      <webElementGuid>ed757419-ae38-4e9a-9892-2fbd5b6924b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swiper-wrapper-997744c1cec46158&quot;)/div[@class=&quot;swiper-slide swiper-slide-active&quot;]/div[@class=&quot;pro-loop&quot;]/div[@class=&quot;pro-loop--wrap&quot;]/div[@class=&quot;pro-loop--head&quot;]/a[@class=&quot;pro-loop--link&quot;]</value>
      <webElementGuid>7c9619b8-cb32-4001-945e-25fd05e1b843</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[contains(@id, 'swiper-wrapper')]/div/div/div/div/a</value>
      <webElementGuid>9ab527bf-9e3f-4f46-bab2-992924a0b73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01')]</value>
      <webElementGuid>2536a81a-d1d6-4223-ae09-4c3e5a370e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/div/a</value>
      <webElementGuid>31fa55f6-0218-4d46-a7a2-a83ec9883a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/products/ao-khoac-2-lop-nam-xanh-reu-aristino-regular-fit-ajk606edp01']</value>
      <webElementGuid>42c56553-1d9d-42b1-abbb-b0c326c7c8bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
