<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_addtocart</name>
   <tag></tag>
   <elementGuidId>f9b79d30-4d44-4377-b86e-97b554882f91</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn-addtocart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn-addtocart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Đặt hàng trước&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>true</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8c2bb13c-db64-4951-adfa-3c783b825cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>faa3070a-1557-4490-87f9-3d300530ea26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn-addtocart</value>
      <webElementGuid>b1ebe7f8-3117-46f2-b1e1-8826425b2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn add-cart</value>
      <webElementGuid>53d56f2b-8540-4dc2-bc92-4991ee6bd90d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đặt hàng trước</value>
      <webElementGuid>edf68e90-c626-4c8d-b3e1-27a51231664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn-addtocart&quot;)</value>
      <webElementGuid>2766d470-ced8-4628-9d3c-df7734777976</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn-addtocart']</value>
      <webElementGuid>e6772ccf-ce3e-4bd6-ae09-dd40873f1bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='productdetail-page']/div/div/div/div/div[2]/div[2]/div[6]/div[2]/button</value>
      <webElementGuid>ed93b51a-17ac-4c50-93c8-366226bcde5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XXL'])[1]/following::button[3]</value>
      <webElementGuid>1ef2acca-e2f5-461a-83c6-2df00dc33b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/following::button[3]</value>
      <webElementGuid>e528258f-c212-4180-a341-55346b65963f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian giao hàng dự kiến'])[1]/preceding::button[2]</value>
      <webElementGuid>0c9a5abe-bc44-4fbb-b9a3-66987e825322</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/button</value>
      <webElementGuid>1f2dc40b-75f7-468a-b114-3ee058784f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn-addtocart' and (text() = 'Đặt hàng trước' or . = 'Đặt hàng trước')]</value>
      <webElementGuid>d9349618-a742-4d8c-b954-e028b69f2c73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
