<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_zoom</name>
   <tag></tag>
   <elementGuidId>9783c508-94b3-4626-961c-a4e40f10a231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fancybox__toolbar__column.is-middle > button.f-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='fancybox-1']/div/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Toggle full-screen mode&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>840983a8-eb99-4bd0-9cd0-3c3a5b076a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>f-button</value>
      <webElementGuid>fdc13064-bf69-490f-a4cf-f3dceff5a9ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Toggle full-screen mode</value>
      <webElementGuid>10b48a86-afbe-4c18-824b-ec29f6eef1d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fancybox-1&quot;)/div[@class=&quot;fancybox__toolbar&quot;]/div[@class=&quot;fancybox__toolbar__column is-middle&quot;]/button[@class=&quot;f-button&quot;]</value>
      <webElementGuid>733378a9-0861-4544-b3c9-656d565b0851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fancybox-1']/div/div[2]/button</value>
      <webElementGuid>12d6bcaf-d69b-4569-8ca5-7a2bf1e2c1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ý kiến phản hồi của bạn sẽ được dùng để góp phần cải thiện Google Dịch'])[1]/following::button[5]</value>
      <webElementGuid>ad2e5a15-5b00-4ffb-b233-f8d9b3dd8ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá bản dịch này'])[1]/following::button[5]</value>
      <webElementGuid>0df08fd3-2c6e-4f74-85d0-8a0abfb38a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đánh giá sản phẩm'])[2]/preceding::button[6]</value>
      <webElementGuid>4ddb7ed6-dabf-41cd-a076-534a86154aee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div[2]/button</value>
      <webElementGuid>a54f8b50-fb7b-49ec-99d8-fb7141573acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@title = 'Toggle full-screen mode']</value>
      <webElementGuid>7cf43bfe-c2e8-435e-953e-13a438f03747</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
