<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_product</name>
   <tag></tag>
   <elementGuidId>435d99f6-695d-4983-9462-7e8c77511553</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pr-gallery--item.swiper-slide.i-2 > a.pr-gallery--aspect-ratio > picture > img.img-default.lazyloading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pr-gallery']/div[2]/a/picture/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(2) > .pr-gallery--aspect-ratio</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1d56846a-1969-40bb-aff9-e66e6fa90248</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-default lazyloading</value>
      <webElementGuid>428007a4-0243-4a3b-8488-177b1f47811f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-src</name>
      <type>Main</type>
      <value>https://cdn.hstatic.net/products/200000887901/dsc00635__2__20c343b22fb140e89f7240801c481da6_debf9318ab7b4619bb59d6b8974fa9fb.jpg</value>
      <webElementGuid>d6b64b8f-8eb1-414e-8ee7-c770a9a67faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Nâu</value>
      <webElementGuid>054c4f58-a062-49d4-838b-15922f949ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn.hstatic.net/products/200000887901/dsc00635__2__20c343b22fb140e89f7240801c481da6_debf9318ab7b4619bb59d6b8974fa9fb.jpg</value>
      <webElementGuid>433f271e-d0fa-41dc-94d0-34f70e7fa197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pr-gallery&quot;)/div[@class=&quot;pr-gallery--item swiper-slide i-2&quot;]/a[@class=&quot;pr-gallery--aspect-ratio&quot;]/picture[1]/img[@class=&quot;img-default lazyloading&quot;]</value>
      <webElementGuid>7ed69f88-cb52-4823-9b62-84d0099c2502</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pr-gallery']/div[2]/a/picture/img</value>
      <webElementGuid>e58c9637-0ae0-4cac-a834-f6d2ed334ff9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Nâu'])[2]</value>
      <webElementGuid>c4aa7392-3c42-42ef-b5ed-28f8bbcb39b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/picture/img</value>
      <webElementGuid>089f54d4-5c59-4b3b-90ac-74735ca70cef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Nâu' and @src = 'https://cdn.hstatic.net/products/200000887901/dsc00635__2__20c343b22fb140e89f7240801c481da6_debf9318ab7b4619bb59d6b8974fa9fb.jpg']</value>
      <webElementGuid>5ec254ef-619a-45bd-836f-d5c09c386563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
