<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>size_XXL</name>
   <tag></tag>
   <elementGuidId>7828a81f-052f-49b3-b705-7599d0f464a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='variant-swatch-2']/div[2]/div[5]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;XXL&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>fe376e39-cfb2-43b5-8c54-1cb68ab8b7b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>aspect-ratio</value>
      <webElementGuid>0e07a421-30b7-434e-b792-34b3152a8544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>XXL</value>
      <webElementGuid>c0c88a01-03f9-4c9f-8927-15fd2b8fe0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XXL</value>
      <webElementGuid>f8f27b85-9cd0-4af6-ac6c-ddea2fe39a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;variant-swatch-2&quot;)/div[@class=&quot;select-swap select-swap--size&quot;]/div[@class=&quot;swatch-element&quot;]/label[@class=&quot;aspect-ratio&quot;]</value>
      <webElementGuid>e1437307-4f5e-44f6-ab8b-e1a76986d680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='variant-swatch-2']/div[2]/div[5]/label</value>
      <webElementGuid>b6c8080a-d789-4219-b992-538b3a01151c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/following::label[1]</value>
      <webElementGuid>33c57184-b5bc-4683-9554-2a0b21dd093e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/following::label[2]</value>
      <webElementGuid>6d3d7a7d-7cff-423b-aebb-c5c201aabfb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt hàng trước'])[1]/preceding::label[1]</value>
      <webElementGuid>b60f7076-d4a0-42cf-b4ec-1d2bb5de5c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thời gian giao hàng dự kiến'])[1]/preceding::label[1]</value>
      <webElementGuid>bcd0bf12-3d01-4a4e-9c4a-322348f31046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='XXL']/parent::*</value>
      <webElementGuid>9c6e6d0e-74c9-448e-bd41-d8735b8c00b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/label</value>
      <webElementGuid>50a4e56b-1e55-4443-8467-5b5a776e4bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'XXL' or . = 'XXL')]</value>
      <webElementGuid>78351833-2ba3-48f7-bdc3-b8c8c44c50a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
